version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: heru
      MONGO_INITDB_ROOT_PASSWORD: heru

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: heru
      ME_CONFIG_MONGODB_ADMINPASSWORD: heru
      ME_CONFIG_MONGODB_URL: mongodb://heru:heru@localhost:27017/
